### Get All Columns of a Board
GET http://localhost:3000/column/board/1

### Get Column by ID
GET http://localhost:3000/column/1

### Create a Column
POST http://localhost:3000/column/board/1
Content-Type: application/json

{
  "name": "Column 4 of Board 1"
}

### Update a Column
PATCH http://localhost:3000/column/1
Content-Type: application/json

{
  "order": 1
}

### Delete a Column
DELETE http://localhost:3000/column/{columnId}

### ! Drag and Drop

### Reorder Columns
PATCH http://localhost:3000/column/move/4?boardId=1&newOrder=10
Content-Type: application/json
