### Sign up user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "test2",
  "email": "test2@test.com",
  "password": "test123"
}

### Sign in user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "test123"
}